### ISSUE TITLE
MovieDemoClipper can obtain start and end times normally, and the save clip prompts creation complete, but no files are generated.

### ISSUE THREAD

**Issue by ejizhan** [nicko88/MovieDemoClipper#1]
hello，nicko
MovieDemoClipper can obtain start and end times normally, and the save clip prompts creation complete, but no files are generated.

![2023-12-28_212524](https://github.com/nicko88/MovieDemoClipper/assets/41534866/985862f9-85bd-4169-923b-61262c90b505)
![2023-12-28_212556](https://github.com/nicko88/MovieDemoClipper/assets/41534866/a526fb1e-a3c7-44b2-bc99-8075377688d1)
![2023-12-28_212630](https://github.com/nicko88/MovieDemoClipper/assets/41534866/bc8daece-bdc4-44dc-82af-5cb8b0a09993)

**Comment by nicko88** [comment]
Do you see the console window pop up when you press OK on Save Clip file prompt?  Maybe it pops up for only a moment and instantly closes.

Perhaps you don’t have ffmpeg.exe in the right place. 

Everything needed should be in the release zip if you just extract it all anywhere and run it from there. 

You can use your own MPC player anywhere, but you must have ffmpeg.exe placed inside a folder named ffmpeg which is located in the same place as MovieDemoClipper.exe

![image](https://github.com/nicko88/MovieDemoClipper/assets/1866075/a2cc9fb7-245c-4308-8827-fc83c6704c1e)

Looking at my code, I guess I did not really check if ffmpeg.exe is found, and I think it will just go to "clip complete" immediately if ffmpeg was not found properly.

I will consider improving my error handling around this in an update.

**Comment by ejizhan** [comment]
thanks.
ffmpeg.exe placed inside a folder named ffmpeg which is located in the same place as MovieDemoClipper.exe.
Is the problem caused by multiple ffmpeg.exe files on my computer?ffmpeg was not found properly.
![2023-12-29_081643](https://github.com/nicko88/MovieDemoClipper/assets/41534866/16a8fb7d-1d6d-4455-bdce-2b9a4648bad7)
![2023-12-29_081619](https://github.com/nicko88/MovieDemoClipper/assets/41534866/7a564dc7-98e4-4d85-b14f-5438d603a2ed)

**Comment by nicko88** [comment]
Oh, I see the problem.

The file you have open is a .mpls file which is a Blu-ray movie playlist file.

This can't be the file that the clipper app is operating on as it's not a video file, it's just a playlist file pointing to video files.

You need to open the actual video file which should be a .m2ts file.  You should be able to find the .m2ts files in the STREAM folder on the disc file structure.

**Comment by ejizhan** [comment]
No problem, thank you very much!
